### ISSUE TITLE
requestOneTimePayment

### ISSUE THREAD

**Issue by SaqibNytro** [smarkets/react-native-paypal#70] opened 2021-02-01 05:21 UTC
try{
const {
                nonce,
                payerId,
                email,
                firstName,
                lastName,
                phone
            } = await requestOneTimePayment(
                token,
                {
                    amount: cartTotalPrice.toString() , // required
                    // // any PayPal supported currency (see here: https://developer.paypal.com/docs/integration/direct/rest/currency-codes/#paypal-account-payments)
                    currency: 'GBP',
                    //
                    localeCode: 'en_GB',
                    // shippingAddressRequired: false,
                    userAction: 'commit', // display 'Pay Now' on the PayPal review page
                    intent: 'authorize',
                }
            ).then( response => {setSuccess (response); consolel.log("successfully gort response .. ") } )
            //  .catch((e) => {
            //     console.log("Error")
            //     console.log(e.message)
            // })
                .catch( error => { console.log("Error => " , error.message)} )

        }catch (e){
            console.log("Request One Time PAyment -> " ,JSON.stringify( e ))
        }

The above is my code and i dont get promise running . Although i do all the transaction . webview closes without showing payment is done . And i couldnot get trace any teansaction being done in sandbox account . 

ANY HELP WILL BE REALLY APPRECIATABLE . THANKS .

**Comment by nzankich** [comment] 2021-02-06 21:30
@SaqibNytro are you receiving the nonce token after calling `requestOneTimePayment`?  This package only covers the first step of the paypal token flow. You will need to take that token and send it to your backend to complete the transaction

I believe this issue is a duplicate of https://github.com/smarkets/react-native-paypal/issues/59
You can see some more details I wrote up in there

Here is the part you'll need to implement https://developers.braintreepayments.com/start/hello-server/ruby#receive-a-payment-method-nonce-from-your-client

**Comment by nzankich** [comment] 2021-02-14 23:33
v 4.1.0 includes an example of the backend implementation (which is needed for transactions to appear in your account).  Try that out and lmk if you're still having issues

**Closed by nzankich** 2021-02-14 23:33 UTC
