### ISSUE TITLE
 Error: Exception in HostObject::get(propName:RNPaypal): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/braintreepayments/api/BraintreeFragment;

### ISSUE THREAD

**Issue by shashitechvalens** [smarkets/react-native-paypal#68] opened 2021-01-15 11:32 UTC
Error: Exception in HostObject::get(propName:RNPaypal): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/braintreepayments/api/BraintreeFragment;

**Comment by nzankich** [comment] 2021-01-19 21:34
@shashitechvalens make sure you have followed step 2 of the setup instructions

```
[Android] Add implementation "com.braintreepayments.api:braintree:3.14.1" in android/app/build.gradle. 
```

**Comment by nzankich** [comment] 2021-01-19 21:34
going to close this as a duplicate of https://github.com/smarkets/react-native-paypal/issues/22

if you're still having issues tag me in there and I can reopen that one

**Closed by nzankich** 2021-01-19 21:34 UTC
