### ISSUE TITLE
Native Code dependancy 

### ISSUE THREAD

**Issue by davekedar** [smarkets/react-native-paypal#2] opened 2018-10-30 12:13 UTC
Is it possible to use this library without writing a single line of code in Native for ios and android?

**Comment by riso** [comment] 2018-10-30 12:33
yup, see the Usage section of the readme. If you run that code, you should get the result shown in the gif. Please notice that we only support the [Checkout](https://developer.paypal.com/docs/checkout/) flow of PayPal atm.

**Comment by davekedar** [comment] 2018-10-30 12:54
can i have example code?

**Comment by davekedar** [comment] 2018-10-30 12:59
![image](https://user-images.githubusercontent.com/11268363/47719619-bde33780-dc71-11e8-9135-f9e4594239dd.png)
 Getting this error.Please help

**Comment by riso** [comment] 2018-10-30 13:31
Apologies, for iOS you need to change some native code. Did you do step 4 (`[iOS] Register a URL scheme in Xcode`) and 5 (`[iOS] Edit your AppDelegate.m`) of the installation?

**Comment by davekedar** [comment] 2018-10-31 04:15
@riso ok thanks, 

I have understood the 5th step, but for 4th step, I am confused what to change and where, if possible guide me, I am sure there are lots of developers who are not iOS native developers and will find the same problem 

![image](https://user-images.githubusercontent.com/11268363/47765788-acda0b00-dcf1-11e8-80dd-2515538d90cd.png)

**Comment by riso** [comment] 2018-10-31 13:42
so as it says in the picture you pasted, in Xcode you should select your project in the project navigator

![image](https://user-images.githubusercontent.com/448304/47791533-da36b100-dd11-11e8-9460-b3aae8601e0b.png)

and then in the main window make sure to highlight the app target like this

![image](https://user-images.githubusercontent.com/448304/47791687-1ff37980-dd12-11e8-9fa5-6fb9254b06c3.png)

and under the tab Info you should find a section called URL Types. There you can press on the `+` button to add a new URL Type like this

![image](https://user-images.githubusercontent.com/448304/47791781-5b8e4380-dd12-11e8-8f7f-a2b6e6d328a4.png)

you need to populate only the URL Schemes field. As explained in the README, **It must be** `<your-app-id>.payments`. You can find the app id under the General tab, Identity section in the Bundle Identifier field.

Let me know if this helps

**Comment by riso** [comment] 2018-11-01 15:15
Coule you please paste your entire AppDelegate.m file?

**Comment by riso** [comment] 2018-11-02 13:42
The problem is that you defined the method `didFinishLaunchingWithOptions` twice, and everything must be within `@implementation`. Try the following instead

```
#import "AppDelegate.h"

#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNPaypal.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [[RNPaypal sharedInstance] configure];
  NSURL *jsCodeLocation;

  jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"QualPros"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
  return [[RNPaypal sharedInstance] application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
}

@end
```

Also, the URL scheme that you need to register is `org.reactjs.native.example.QualPros.payments`, not `org.reactjs.native.example.QualPros.payment` (final s is missing).

your test url will be `org.reactjs.native.example.QualPros.payments://test`, if it works it should open your app. You need to open it from safari within the device / emulator that has your app installed

**Comment by davekedar** [comment] 2018-11-05 11:09
I think I am very close, but it is still giving me errors, can I share my code? Please help me

**Comment by riso** [comment] 2018-11-06 10:18
Sure, feel free to share your code. What error are you getting now?

**Comment by davekedar** [comment] 2018-11-12 12:43
any update on the same? Can I contact you from outside? please reply and plz help me get this done

**Comment by davekedar** [comment] 2018-11-12 12:46
http://prntscr.com/lhcwd1
getting this error

**Comment by riso** [comment] 2018-11-12 15:03
Looking at your code, it seems like you're setting React state in a wrong way, you should always call setState to do so.

that being said I also suspect your code to get a token might be wrong. can you just try passing the test token that PayPal provides in [their documentation](https://developers.braintreepayments.com/start/hello-client/ios/v3#try-it-now)? 


just pass the following as the first parameter to `requestOneTimePayment` and let me know how it goes

'eyJ2ZXJzaW9uIjoyLCJhdXRob3JpemF0aW9uRmluZ2VycHJpbnQiOiJkNzEwMDFlMTM4NzVhMjgxZGE4MmQ1YmI1MTZhZmJhMzdjMjRmYmYxMDRkMzM2ZTM2YTYzZWVkNWNhMTRkYTZkfGNyZWF0ZWRfYXQ9MjAxOC0xMS0xMlQxNTowMDoyMS40ODQ2NTQwMzUrMDAwMFx1MDAyNm1lcmNoYW50X2lkPTM0OHBrOWNnZjNiZ3l3MmJcdTAwMjZwdWJsaWNfa2V5PTJuMjQ3ZHY4OWJxOXZtcHIiLCJjb25maWdVcmwiOiJodHRwczovL2FwaS5zYW5kYm94LmJyYWludHJlZWdhdGV3YXkuY29tOjQ0My9tZXJjaGFudHMvMzQ4cGs5Y2dmM2JneXcyYi9jbGllbnRfYXBpL3YxL2NvbmZpZ3VyYXRpb24iLCJncmFwaFFMIjp7InVybCI6Imh0dHBzOi8vcGF5bWVudHMuc2FuZGJveC5icmFpbnRyZWUtYXBpLmNvbS9ncmFwaHFsIiwiZGF0ZSI6IjIwMTgtMDUtMDgifSwiY2hhbGxlbmdlcyI6W10sImVudmlyb25tZW50Ijoic2FuZGJveCIsImNsaWVudEFwaVVybCI6Imh0dHBzOi8vYXBpLnNhbmRib3guYnJhaW50cmVlZ2F0ZXdheS5jb206NDQzL21lcmNoYW50cy8zNDhwazljZ2YzYmd5dzJiL2NsaWVudF9hcGkiLCJhc3NldHNVcmwiOiJodHRwczovL2Fzc2V0cy5icmFpbnRyZWVnYXRld2F5LmNvbSIsImF1dGhVcmwiOiJodHRwczovL2F1dGgudmVubW8uc2FuZGJveC5icmFpbnRyZWVnYXRld2F5LmNvbSIsImFuYWx5dGljcyI6eyJ1cmwiOiJodHRwczovL29yaWdpbi1hbmFseXRpY3Mtc2FuZC5zYW5kYm94LmJyYWludHJlZS1hcGkuY29tLzM0OHBrOWNnZjNiZ3l3MmIifSwidGhyZWVEU2VjdXJlRW5hYmxlZCI6dHJ1ZSwicGF5cGFsRW5hYmxlZCI6dHJ1ZSwicGF5cGFsIjp7ImRpc3BsYXlOYW1lIjoiQWNtZSBXaWRnZXRzLCBMdGQuIChTYW5kYm94KSIsImNsaWVudElkIjpudWxsLCJwcml2YWN5VXJsIjoiaHR0cDovL2V4YW1wbGUuY29tL3BwIiwidXNlckFncmVlbWVudFVybCI6Imh0dHA6Ly9leGFtcGxlLmNvbS90b3MiLCJiYXNlVXJsIjoiaHR0cHM6Ly9hc3NldHMuYnJhaW50cmVlZ2F0ZXdheS5jb20iLCJhc3NldHNVcmwiOiJodHRwczovL2NoZWNrb3V0LnBheXBhbC5jb20iLCJkaXJlY3RCYXNlVXJsIjpudWxsLCJhbGxvd0h0dHAiOnRydWUsImVudmlyb25tZW50Tm9OZXR3b3JrIjp0cnVlLCJlbnZpcm9ubWVudCI6Im9mZmxpbmUiLCJ1bnZldHRlZE1lcmNoYW50IjpmYWxzZSwiYnJhaW50cmVlQ2xpZW50SWQiOiJtYXN0ZXJjbGllbnQzIiwiYmlsbGluZ0FncmVlbWVudHNFbmFibGVkIjp0cnVlLCJtZXJjaGFudEFjY291bnRJZCI6ImFjbWV3aWRnZXRzbHRkc2FuZGJveCIsImN1cnJlbmN5SXNvQ29kZSI6IlVTRCJ9LCJtZXJjaGFudElkIjoiMzQ4cGs5Y2dmM2JneXcyYiIsInZlbm1vIjoib2ZmIn0='

**Comment by riso** [comment] 2018-11-20 10:57
@davekedar were you able to solve your problem? Closing this for now.

**Closed by riso** 2018-11-20 10:57 UTC
