### ISSUE TITLE
Tokenization Key or client token was invalid.

### ISSUE THREAD

**Issue by mohamedadlyy** [smarkets/react-native-paypal#38] opened 2020-07-21 12:50 UTC
dear can anyone help me to fix this problem 
Possible Unhandled Promise Rejection (id: 0):
Error: Tokenization Key or client token was invalid.

**Comment by barinascode** [comment] 2020-07-21 21:06
x2

**Comment by nzankich** [comment] 2020-08-19 01:16
Closing as duplicate of https://github.com/smarkets/react-native-paypal/issues/32

**Closed by nzankich** 2020-08-19 01:16 UTC
